import { createTimelineEvent } from './timelineAdapters';
import type { TimelineEvent, TimelineEventInput } from './timelineTypes';

const atRelativeTime = (
  referenceDate: Date,
  dayOffset: number,
  hour: number,
  minute = 0,
) => {
  const date = new Date(
    referenceDate.getFullYear(),
    referenceDate.getMonth(),
    referenceDate.getDate() + dayOffset,
    hour,
    minute,
  );
  return date.toISOString();
};

export const createPlaceholderTimelineEvents = (
  referenceDate = new Date(),
): TimelineEvent[] => {
  // TODO: Backend Integration — replace this source with adapted module records.
  const events: TimelineEventInput[] = [
    {
      id: 'timeline-vital-1',
      type: 'vital',
      title: 'Morning vitals recorded',
      subtitle: 'Home monitoring',
      description: 'Blood pressure and resting heart rate were within target range.',
      timestamp: atRelativeTime(referenceDate, 0, 8, 15),
      status: 'completed',
      priority: 'normal',
      metadata: { value: '118/76', unit: 'mmHg', location: 'Home' },
      notes: 'Resting heart rate: 72 bpm.',
      linkedModule: 'Vitals',
      keywords: ['blood pressure', 'heart rate', 'monitoring'],
      tags: ['vitals', 'routine'],
    },
    {
      id: 'timeline-medicine-1',
      type: 'medicine',
      title: 'Morning medicine scheduled',
      subtitle: 'Metformin · 500 mg',
      description: 'Take one tablet with breakfast as prescribed.',
      timestamp: atRelativeTime(referenceDate, 0, 9),
      status: 'pending',
      priority: 'normal',
      metadata: { medicine: 'Metformin', value: '500 mg' },
      linkedModule: 'Medicines',
      keywords: ['tablet', 'breakfast', 'diabetes'],
      tags: ['medication', 'daily'],
    },
    {
      id: 'timeline-emergency-1',
      type: 'emergency',
      title: 'Critical allergy alert reviewed',
      subtitle: 'Clinical safety alert',
      description: 'Penicillin allergy was reconfirmed for emergency visibility.',
      timestamp: atRelativeTime(referenceDate, 0, 11, 30),
      status: 'critical',
      priority: 'critical',
      metadata: { medicine: 'Penicillin', location: 'Medical profile' },
      notes: 'Avoid penicillin-class antibiotics.',
      linkedModule: 'Emergency',
      keywords: ['allergy', 'critical', 'safety'],
      tags: ['emergency', 'allergy', 'alert'],
    },
    {
      id: 'timeline-appointment-1',
      type: 'appointment',
      title: 'Cardiology follow-up',
      subtitle: 'Dr. Ananya Rao',
      description: 'Routine review of blood pressure trends and medication response.',
      timestamp: atRelativeTime(referenceDate, 1, 10, 30),
      status: 'upcoming',
      priority: 'high',
      metadata: {
        doctor: 'Dr. Ananya Rao',
        hospital: 'HealthSphere Heart Centre',
        location: 'Outpatient Wing B',
      },
      linkedModule: 'Appointments',
      keywords: ['cardiology', 'consultation', 'follow-up'],
      tags: ['appointment', 'cardiology', 'dr-ananya'],
    },
    {
      id: 'timeline-report-1',
      type: 'report',
      title: 'Lipid profile report added',
      subtitle: 'Diagnostic laboratory',
      description: 'Recent cholesterol panel was added to the longitudinal record.',
      timestamp: atRelativeTime(referenceDate, -1, 16, 10),
      status: 'completed',
      priority: 'normal',
      metadata: {
        report: 'Lipid Profile',
        hospital: 'CityCare Diagnostics',
      },
      linkedModule: 'Medical Reports',
      keywords: ['cholesterol', 'LDL', 'HDL', 'laboratory'],
      tags: ['lab-result', 'cholesterol'],
      attachments: [
        { name: 'Lipid_Profile_July2026.pdf', type: 'application/pdf', size: '1.2 MB' },
      ],
    },
    {
      id: 'timeline-vaccination-1',
      type: 'vaccination',
      title: 'Annual Influenza Vaccine',
      subtitle: 'Preventative Care',
      description: 'Received quadrivalent seasonal flu vaccination dose.',
      timestamp: atRelativeTime(referenceDate, -2, 14, 0),
      status: 'completed',
      priority: 'normal',
      metadata: {
        doctor: 'Dr. Rajesh Sharma',
        hospital: 'Apollo Hospital',
        value: '0.5 mL',
      },
      notes: 'No immediate adverse reactions observed during 15 min wait.',
      linkedModule: 'Vaccinations',
      keywords: ['flu', 'vaccine', 'immunization'],
      tags: ['vaccine', 'immunization', 'preventative'],
      attachments: [
        { name: 'Flu_Vaccine_Certificate.pdf', type: 'application/pdf', size: '450 KB' },
      ],
    },
    {
      id: 'timeline-lab-1',
      type: 'lab-test',
      title: 'HbA1c & Fasting Blood Sugar',
      subtitle: 'CityCare Diagnostics',
      description: 'Comprehensive glycemic control laboratory test panel.',
      timestamp: atRelativeTime(referenceDate, -3, 9, 30),
      status: 'completed',
      priority: 'high',
      metadata: {
        report: 'HbA1c Panel',
        hospital: 'CityCare Diagnostics',
        doctor: 'Dr. Ananya Rao',
        value: '5.8%',
        unit: 'HbA1c',
      },
      linkedModule: 'Medical Reports',
      keywords: ['diabetes', 'hba1c', 'glucose', 'lab'],
      tags: ['lab-test', 'diabetes'],
      attachments: [
        { name: 'HbA1c_Lab_Report.pdf', type: 'application/pdf', size: '890 KB' },
      ],
    },
    {
      id: 'timeline-health-log-1',
      type: 'health-log',
      title: 'Daily wellness log',
      subtitle: 'Patient-reported update',
      description: 'Energy levels improved with no dizziness or headache reported.',
      timestamp: atRelativeTime(referenceDate, -3, 19),
      status: 'completed',
      priority: 'low',
      metadata: { value: 'Energy 8/10', location: 'Home' },
      linkedModule: 'Health Logs',
      keywords: ['wellness', 'symptoms', 'energy'],
      tags: ['wellness', 'log'],
    },
    {
      id: 'timeline-reminder-1',
      type: 'reminder',
      title: 'Evening dose reminder missed',
      subtitle: 'Atorvastatin · 10 mg',
      description: 'The scheduled medication reminder was not confirmed.',
      timestamp: atRelativeTime(referenceDate, -5, 21),
      status: 'missed',
      priority: 'high',
      metadata: { medicine: 'Atorvastatin', value: '10 mg' },
      linkedModule: 'Reminders',
      keywords: ['dose', 'medication adherence', 'evening'],
      tags: ['reminder', 'missed'],
    },
    {
      id: 'timeline-bmi-1',
      type: 'bmi',
      title: 'BMI updated',
      subtitle: 'Routine health measurement',
      description: 'BMI remained stable within the recorded wellness trend.',
      timestamp: atRelativeTime(referenceDate, -12, 7, 45),
      status: 'completed',
      priority: 'normal',
      metadata: { value: '23.4', unit: 'kg/m²' },
      linkedModule: 'Profile',
      keywords: ['BMI', 'body mass index'],
      tags: ['vitals', 'bmi'],
    },
    {
      id: 'timeline-weight-1',
      type: 'weight',
      title: 'Weight measurement recorded',
      subtitle: 'Home scale',
      description: 'Weight decreased by 0.6 kg compared with the previous entry.',
      timestamp: atRelativeTime(referenceDate, -20, 7, 30),
      status: 'completed',
      priority: 'low',
      metadata: { value: '68.2', unit: 'kg', location: 'Home' },
      linkedModule: 'Profile',
      keywords: ['weight', 'trend', 'measurement'],
      tags: ['weight', 'vitals'],
    },
    {
      id: 'timeline-blood-1',
      type: 'blood-donation',
      title: 'Blood donation eligibility recorded',
      subtitle: 'O+ whole blood',
      description: 'Eligibility screening was completed for the next donation cycle.',
      timestamp: atRelativeTime(referenceDate, -36, 13),
      status: 'completed',
      priority: 'normal',
      metadata: {
        value: 'O+',
        hospital: 'Regional Blood Centre',
      },
      linkedModule: 'Blood & Organ',
      keywords: ['donation', 'blood group', 'eligibility'],
      tags: ['blood-donation', 'screening'],
    },
    {
      id: 'timeline-note-1',
      type: 'note',
      title: 'Care plan note archived',
      subtitle: 'Clinical note',
      description: 'Previous nutrition guidance was superseded by the current plan.',
      timestamp: atRelativeTime(referenceDate, -68, 15, 20),
      status: 'archived',
      priority: 'low',
      metadata: { doctor: 'Dr. Meera Shah' },
      notes: 'Retained for longitudinal clinical context.',
      linkedModule: 'Clinical Notes',
      keywords: ['nutrition', 'care plan'],
      tags: ['care-plan', 'nutrition'],
    },
    {
      id: 'timeline-custom-1',
      type: 'custom',
      title: 'Travel health preparation',
      subtitle: 'Personal health event',
      description: 'Created a checklist for medicines and documents before travel.',
      timestamp: atRelativeTime(referenceDate, -95, 18),
      status: 'cancelled',
      priority: 'low',
      metadata: { location: 'Personal record' },
      linkedModule: 'Custom Events',
      keywords: ['travel', 'checklist', 'documents'],
      tags: ['custom', 'travel'],
    },
  ];

  return events.map(createTimelineEvent);
};
